name: REUSE Compliance Check

on:
  pull_request:
    types: [opened, reopened]
  schedule:
    - cron: "0 0 * * *"

jobs:
  markdown-link-check:
    uses: tracetronic/.github/.github/workflows/close-fork-prs.yml@main
