name: Auto Create Pull Request

on:
  workflow_call:
    inputs:
      base:
        description: "The base branch to merge the pull request"
        required: false
        type: string
        default: main

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create PR Title
        id: pr-title
        run: |
          branch_name=${GITHUB_REF_NAME}

          # get pr description with issue number
          if [[ ${branch_name} =~ i([0-9]+) ]]; then
            issue_number="${BASH_REMATCH[1]}"
            branch_name=$(echo ${branch_name} | sed 's/i[0-9]*_//')
            echo "PR_DESCRIPTION=Resolves #${issue_number}" >> $GITHUB_ENV
          else
            echo "PR_DESCRIPTION=No issue reference found" >> $GITHUB_ENV
          fi

          # format pr title from branch name (capitalization, replace dashes with spaces)
          echo "PR_TITLE=$(echo ${branch_name} | sed 's/\b\(.\)/\u\1/g' | sed 's/-/ /g')" >> $GITHUB_ENV
      - name: Create Pull Request
        run: |
          github_token="${{ secrets.GITHUB_TOKEN }}"
          repo_owner="${{ github.repository_owner }}"
          repo_name="${{ github.repository }}"
          head="${{ github.ref }}"

          # create pr
          payload=$(printf '{"title":"%s","body":"%s","head":"%s","base":"%s"}' "${{ env.PR_TITLE }}" "${{ env.PR_DESCRIPTION }}" "${head}" "${{ inputs.base }}")
          curl -L -s -X POST -H "Authorization: Bearer ${github_token}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d "$payload" \
            "https://api.github.com/repos/${repo_owner}/${repo_name}/pulls"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
